language: php

addons:
  postgresql: "9.5"
  firefox: "47.0.1"
  apt:
    packages:
      - ldap-utils
      - slapd
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.1
  - 7.2
  - 7.3

services:
 - mysql

env:
  global:
    - IGNORE_NAMES=sync_test.php
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=mysqli MOODLE_BRANCH=master

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  exclude:
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->auth = "manual,ldap";'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_HOST_URL", "ldap://localhost:3389");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_BIND_DN", "cn=admin,dc=example,dc=com");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_BIND_PW", "password");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_DOMAIN", "dc=example,dc=com");'

before_script:
  - mkdir /tmp/slapd
  - slapd -f moodle/local/ldap/tests/fixtures/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -H ldap://127.0.0.1:3389 -D "cn=admin,dc=example,dc=com" -w password -f moodle/local/ldap/tests/fixtures/bootstrap.ldif

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
